"""tact-meetings — meeting advance reminders on top of the existing cron scheduler.

The model extracts the fields from the manager's message and calls the ``meeting`` tool; every
reply the manager sees is formatted here, so a field the manager did not mention always reads
``NOT MENTIONED`` and is never filled in by the model.

Each logged meeting becomes two one-shot, ``no_agent`` cron jobs (no LLM at fire time) delivered
to the chat the meeting was logged from: the advance reminder 10 minutes before (or right away when the
meeting is closer than that) and a short reminder at start time. Cron jobs already persist in
``<home>/cron/jobs.json`` and survive a restart; the meetings themselves live in
``<home>/meetings/meetings.db`` so ``/meetings`` and ``/cancel <id>`` can list and remove them.
The job script checks the meeting is still scheduled before printing, so a cancelled meeting
stays silent even if removing its jobs failed.
"""

from __future__ import annotations

import json
import logging
import math
import sqlite3
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional
from zoneinfo import ZoneInfo

logger = logging.getLogger(__name__)

TZ = ZoneInfo("Asia/Riyadh")
CARD_LEAD = timedelta(minutes=10)
NOT_MENTIONED = "NOT MENTIONED"

_SCRIPT_TEMPLATE = '''\
# Generated by the tact-meetings plugin: prints this message unless the meeting was cancelled.
import sqlite3
import sys

try:
    with sqlite3.connect({db!r}) as con:
        row = con.execute("SELECT status FROM meetings WHERE id = ?", ({meeting_id},)).fetchone()
except sqlite3.Error:
    row = ("scheduled",)
if row is None or row[0] != "scheduled":
    sys.exit(0)
print({text!r})
'''


# -- storage -----------------------------------------------------------------------------------

def _home() -> Path:
    from hermes_constants import get_hermes_home
    return get_hermes_home()


def _db_path() -> Path:
    path = _home() / "meetings" / "meetings.db"
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


def _connect() -> sqlite3.Connection:
    con = sqlite3.connect(_db_path())
    con.row_factory = sqlite3.Row
    con.execute(
        "CREATE TABLE IF NOT EXISTS meetings ("
        " id INTEGER PRIMARY KEY AUTOINCREMENT,"
        " platform TEXT, chat_id TEXT,"
        " starts_at TEXT NOT NULL,"
        " attendees TEXT, topic TEXT, red_flags TEXT NOT NULL, key_points TEXT NOT NULL,"
        " card_job_id TEXT, reminder_job_id TEXT,"
        " status TEXT NOT NULL DEFAULT 'scheduled',"
        " created_at TEXT NOT NULL)")
    return con


def _script_rel(meeting_id: int, kind: str) -> str:
    # Relative to <home>/scripts/, the only place cron runs scripts from.
    return f"tact_meetings/meeting_{meeting_id}_{kind}.py"


def _script_path(meeting_id: int, kind: str) -> Path:
    return _home() / "scripts" / _script_rel(meeting_id, kind)


def _chat() -> tuple[str, str]:
    from gateway.session_context import get_session_env
    return get_session_env("HERMES_SESSION_PLATFORM"), get_session_env("HERMES_SESSION_CHAT_ID")


# -- formatting --------------------------------------------------------------------------------

def _clean(value: Any) -> str:
    return " ".join(str(value or "").split())


def _clean_list(values: Any) -> List[str]:
    if isinstance(values, str):
        values = [values]
    return [c for c in (_clean(v) for v in (values or [])) if c]


def _or_missing(value: str) -> str:
    return value or NOT_MENTIONED


def _fmt_time(dt: datetime) -> str:
    return f"{dt.hour % 12 or 12}:{dt.minute:02d} {'AM' if dt.hour < 12 else 'PM'}"


def _fmt_day(dt: datetime, now: datetime, short: bool = False) -> str:
    day = f"{dt.strftime('%a' if short else '%A')} {dt.strftime('%b')} {dt.day}"
    return day if dt.year == now.year else f"{day} {dt.year}"


def _bullets(items: List[str]) -> str:
    return "\n".join(f"- {item}" for item in (items or [NOT_MENTIONED]))


def _joined(items: List[str]) -> str:
    return "; ".join(items) or NOT_MENTIONED


def advance_reminder(attendees: str, starts_at: datetime, red_flags: List[str],
                     key_points: List[str], minutes_left: int) -> str:
    lead = (f"meeting in {minutes_left} minute{'' if minutes_left == 1 else 's'}"
            if minutes_left >= 1 else "meeting starting now")
    return (f"⏰ Reminder: {lead}\n"
            f"👥 With: {_or_missing(attendees)}\n"
            f"🕒 Time: {_fmt_time(starts_at)}\n"
            f"🎯 Key points:\n{_bullets(key_points)}\n"
            f"🚩 Red flags:\n{_bullets(red_flags)}")


def start_reminder(attendees: str, topic: str, key_points: List[str]) -> str:
    top = key_points[0] if key_points else NOT_MENTIONED
    return (f"🔔 Your meeting with {_or_missing(attendees)} about {_or_missing(topic)} "
            f"is starting now. Top priority: {top}")


def _parse_start(raw: str) -> datetime:
    dt = datetime.fromisoformat(_clean(raw).replace(" ", "T").replace("Z", "+00:00"))
    # Times the manager gives are Riyadh wall-clock; an explicit offset is honoured.
    return dt.replace(tzinfo=TZ) if dt.tzinfo is None else dt.astimezone(TZ)


# -- operations --------------------------------------------------------------------------------

def _schedule_message(meeting_id: int, kind: str, text: str, run_at: datetime) -> str:
    from cron.scheduler import create_job_with_scheduler_registration
    from tools.cronjob_job_args import _origin_from_env

    path = _script_path(meeting_id, kind)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        _SCRIPT_TEMPLATE.format(db=str(_db_path()), meeting_id=meeting_id, text=text),
        encoding="utf-8")
    schedule = run_at.isoformat(timespec="seconds")
    job = create_job_with_scheduler_registration(
        prompt="", schedule=schedule, name=f"Meeting #{meeting_id} {kind}", repeat=1,
        deliver="origin", origin=_origin_from_env(schedule),
        script=_script_rel(meeting_id, kind), no_agent=True)
    return job["id"]


def log_meeting(start: str, attendees: Any = None, topic: Any = None, red_flags: Any = None,
                key_points: Any = None, now: Optional[datetime] = None) -> Dict[str, Any]:
    now = (now or datetime.now(TZ)).astimezone(TZ)
    if not _clean(start):
        return {"success": False, "error": "No meeting date/time. Ask the manager when the meeting is."}
    try:
        starts_at = _parse_start(start)
    except ValueError:
        return {"success": False,
                "error": f"Could not read the meeting time {start!r}. Ask the manager for the date and time."}
    if starts_at <= now:
        return {"success": False,
                "error": f"{_fmt_day(starts_at, now)}, {_fmt_time(starts_at)} has already passed. "
                         "Ask the manager for the correct date and time."}

    attendees_s, topic_s = _clean(attendees), _clean(topic)
    flags, points = _clean_list(red_flags), _clean_list(key_points)
    card_at = max(starts_at - CARD_LEAD, now)
    card_now = card_at == now
    # Keep the reminder one tick after an immediate card so the two never race in one tick.
    reminder_at = max(starts_at, card_at + timedelta(minutes=1))
    minutes_left = math.ceil((starts_at - card_at).total_seconds() / 60)
    platform, chat_id = _chat()

    with _connect() as con:
        meeting_id = con.execute(
            "INSERT INTO meetings (platform, chat_id, starts_at, attendees, topic, red_flags,"
            " key_points, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (platform, chat_id, starts_at.isoformat(), attendees_s, topic_s, json.dumps(flags),
             json.dumps(points), now.isoformat())).lastrowid
    try:
        card_job = _schedule_message(
            meeting_id, "card", advance_reminder(attendees_s, starts_at, flags, points, minutes_left),
            card_at)
        reminder_job = _schedule_message(
            meeting_id, "reminder", start_reminder(attendees_s, topic_s, points), reminder_at)
    except Exception as exc:
        logger.exception("tact-meetings: scheduling meeting #%s failed", meeting_id)
        cancel_meeting(meeting_id, any_chat=True)
        return {"success": False, "error": f"Could not schedule the reminders: {exc}"}
    with _connect() as con:
        con.execute("UPDATE meetings SET card_job_id = ?, reminder_job_id = ? WHERE id = ?",
                    (card_job, reminder_job, meeting_id))

    advance = ("advance reminder sending now (meeting is less than 10 minutes away)" if card_now
               else f"10 min before ({_fmt_time(card_at)})")
    confirmation = (
        "✅ Logged\n"
        f"👥 With: {_or_missing(attendees_s)}\n"
        f"🕒 Time: {_fmt_day(starts_at, now)}, {_fmt_time(starts_at)}\n"
        f"🎯 Key points: {_joined(points)}\n"
        f"🚩 Red flags: {_joined(flags)}\n"
        f"⏰ Reminders: {advance} and at start ({_fmt_time(reminder_at)}). "
        f"ID {meeting_id}, /cancel {meeting_id} to cancel")
    return {"success": True, "meeting_id": meeting_id, "confirmation": confirmation}


def _chat_filter(any_chat: bool) -> tuple[str, tuple]:
    platform, chat_id = _chat()
    if any_chat or not chat_id:
        return "", ()
    return " AND platform = ? AND chat_id = ?", (platform, chat_id)


def upcoming(now: Optional[datetime] = None) -> List[sqlite3.Row]:
    now = (now or datetime.now(TZ)).astimezone(TZ)
    where, params = _chat_filter(False)
    with _connect() as con:
        rows = con.execute(
            f"SELECT * FROM meetings WHERE status = 'scheduled'{where} ORDER BY starts_at", params).fetchall()
    return [r for r in rows if datetime.fromisoformat(r["starts_at"]) > now]


def list_text(now: Optional[datetime] = None) -> str:
    now = (now or datetime.now(TZ)).astimezone(TZ)
    rows = upcoming(now)
    if not rows:
        return "📅 No upcoming meetings."
    lines = ["📅 Upcoming meetings:"]
    for r in rows:
        dt = datetime.fromisoformat(r["starts_at"]).astimezone(TZ)
        lines.append(f"#{r['id']} — {_fmt_day(dt, now, short=True)}, {_fmt_time(dt)} with "
                     f"{_or_missing(r['attendees'])} — {_or_missing(r['topic'])}")
    lines.append("Cancel one with /cancel <id>.")
    return "\n".join(lines)


def cancel_meeting(meeting_id: Any, any_chat: bool = False) -> Dict[str, Any]:
    from cron.jobs import remove_job

    try:
        meeting_id = int(str(meeting_id).strip().lstrip("#"))
    except ValueError:
        return {"success": False, "error": "Usage: /cancel <id> (see /meetings for ids)."}
    where, params = _chat_filter(any_chat)
    with _connect() as con:
        row = con.execute(f"SELECT * FROM meetings WHERE id = ? AND status = 'scheduled'{where}",
                          (meeting_id, *params)).fetchone()
        if row is None:
            return {"success": False, "error": f"No scheduled meeting #{meeting_id}. See /meetings."}
        con.execute("UPDATE meetings SET status = 'cancelled' WHERE id = ?", (meeting_id,))
    for job_id in (row["card_job_id"], row["reminder_job_id"]):
        if job_id:
            remove_job(job_id)
    for kind in ("card", "reminder"):
        _script_path(meeting_id, kind).unlink(missing_ok=True)
    dt = datetime.fromisoformat(row["starts_at"]).astimezone(TZ)
    return {"success": True, "message":
            f"❌ Cancelled meeting #{meeting_id} ({_fmt_day(dt, datetime.now(TZ), short=True)}, "
            f"{_fmt_time(dt)} with {_or_missing(row['attendees'])}). Its advance reminder and start reminder are removed."}


# -- tool + slash commands ---------------------------------------------------------------------

MEETING_SCHEMA = {
    "name": "meeting",
    "description": (
        "Log an upcoming meeting and schedule its advance reminder (10 min before) and start-time "
        "reminder, or list/cancel logged meetings. Use this instead of cronjob for meetings. "
        "Pass ONLY what the manager said; leave any field they did not mention empty, never guess. "
        "If the date or time is missing or unclear, do not call log: ask the manager first. "
        "After log succeeds, reply with the returned `confirmation` text exactly as given."),
    "parameters": {
        "type": "object",
        "properties": {
            "action": {"type": "string", "enum": ["log", "list", "cancel"]},
            "start": {"type": "string", "description":
                      "log: meeting start as YYYY-MM-DDTHH:MM in Asia/Riyadh local time."},
            "attendees": {"type": "string", "description": "log: who the meeting is with, as said."},
            "topic": {"type": "string", "description": "log: what the meeting is about, as said."},
            "red_flags": {"type": "array", "items": {"type": "string"},
                          "description": "log: risks/things to watch out for, one per item."},
            "key_points": {"type": "array", "items": {"type": "string"},
                           "description": "log: points the manager must deliver, most important first."},
            "meeting_id": {"type": "integer", "description": "cancel: the meeting id."},
        },
        "required": ["action"],
    },
}


def _handle_meeting(args: Dict[str, Any], **_kw) -> str:
    action = args.get("action")
    if action == "log":
        result = log_meeting(args.get("start", ""), args.get("attendees"), args.get("topic"),
                             args.get("red_flags"), args.get("key_points"))
    elif action == "list":
        result = {"success": True, "meetings": list_text()}
    elif action == "cancel":
        result = cancel_meeting(args.get("meeting_id"))
    else:
        result = {"success": False, "error": "action must be log, list or cancel"}
    return json.dumps(result, ensure_ascii=False)


def _cmd_meetings(_raw_args: str) -> str:
    return list_text()


def _cmd_cancel(raw_args: str) -> str:
    result = cancel_meeting(raw_args)
    return result.get("message") or result["error"]


def register(ctx) -> None:
    ctx.register_tool(name="meeting", toolset="meetings", schema=MEETING_SCHEMA,
                      handler=_handle_meeting, emoji="⚔️",
                      description="Log meetings with an advance reminder and a start reminder")
    ctx.register_command("meetings", _cmd_meetings, description="List upcoming meetings")
    ctx.register_command("cancel", _cmd_cancel, description="Cancel a logged meeting",
                         args_hint="<id>")
